### ISSUE TITLE
AssertionError in find_options_for_region with hexagonal room

### ISSUE THREAD

**Issue by glennmatthews** [glennmatthews/aagen#58]
````
bin/aagen -s 780508437
Verbosity set to 40
Random seed: 780508437
Generating new dungeon!
Adding initial entrance stairs (d4)
4	Stairs descend to the east
Generating a random room...
Rolling shape and size for a Room (d20)
20	Something unusual!
Generating unusual room size (d20)...
18	Add 2000 square feet and roll again!
Generating unusual room size (d20)...
11	2,700 square feet
+ 2,000 = 4,700 square feet
Generating unusual shape (d20)...
17	A hexagon
WARNING:shapely.geos:Self-intersection at or near point 25 55
WARNING:shapely.geos:Self-intersection at or near point 15 45
WARNING:shapely.geos:Self-intersection at or near point 5 35
WARNING:shapely.geos:Self-intersection at or near point 5 25
WARNING:shapely.geos:Self-intersection at or near point 15 15
WARNING:shapely.geos:Self-intersection at or near point 25 5
Traceback (most recent call last):
  File "bin/aagen", line 148, in <module>
    main()
  File "bin/aagen", line 76, in main
    dungeon_generator = DungeonGenerator(dungeon_map, args.seed)
  File "/Users/glmatthe/Documents/Personal/AAGen/aagen/generator.py", line 103, in __init__
    self.generate_room(Region.ROOM, stairs_to_room)
  File "/Users/glmatthe/Documents/Personal/AAGen/aagen/generator.py", line 494, in generate_room
    polygons, connection)
  File "/Users/glmatthe/Documents/Personal/AAGen/aagen/map.py", line 461, in find_options_for_region
    .format(dx=dx, dy=dy)
AssertionError: Should be grid aligned but is not (-5.0, -30.0)
````

**Comment by glennmatthews** [comment]
No longer seen with latest libraries:

```
$ bin/aagen -s 780508437
Verbosity set to 40
Random seed: 780508437
Generating new dungeon!
Adding initial entrance stairs (d4)
4   Stairs descend to the east
Generating a random room...
Rolling shape and size for a Room (d20)
20  Something unusual!
Generating unusual room size (d20)...
18  Add 2000 square feet and roll again!
Generating unusual room size (d20)...
11  2,700 square feet
+ 2,000 = 4,700 square feet
Generating unusual shape (d20)...
17  A hexagon
Self-intersection at or near point 25 55
WARNING:shapely.geos:Self-intersection at or near point 25 55
Self-intersection at or near point 15 45
WARNING:shapely.geos:Self-intersection at or near point 15 45
Self-intersection at or near point 5 35
WARNING:shapely.geos:Self-intersection at or near point 5 35
Self-intersection at or near point 5 25
WARNING:shapely.geos:Self-intersection at or near point 5 25
Self-intersection at or near point 15 15
WARNING:shapely.geos:Self-intersection at or near point 15 15
Self-intersection at or near point 25 5
WARNING:shapely.geos:Self-intersection at or near point 25 5
Self-intersection at or near point 35 75
WARNING:shapely.geos:Self-intersection at or near point 35 75
Self-intersection at or near point 25 65
WARNING:shapely.geos:Self-intersection at or near point 25 65
Self-intersection at or near point 15 55
WARNING:shapely.geos:Self-intersection at or near point 15 55
Self-intersection at or near point 5 45
WARNING:shapely.geos:Self-intersection at or near point 5 45
Self-intersection at or near point 5 35
WARNING:shapely.geos:Self-intersection at or near point 5 35
Self-intersection at or near point 15 25
WARNING:shapely.geos:Self-intersection at or near point 15 25
Self-intersection at or near point 25 15
WARNING:shapely.geos:Self-intersection at or near point 25 15
Self-intersection at or near point 35 5
WARNING:shapely.geos:Self-intersection at or near point 35 5
Generating number of exits...
12  Larger than 1200 square feet, so it has 1 exit(s)
Generating exit #1
Generating exit location...
2   Opposite the entrance (east)
```
